name: Release
on: workflow_dispatch
jobs:
  Android:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: 18

      - name: Setup Android SDK
        uses: android-actions/setup-android@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 > /dev/null
          haxelib install lime 7.9.0
          haxelib install flixel 4.11.0
          haxelib install flixel-addons 2.11.0
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install newgrounds
          haxelib install openfl 9.1.0
          haxelib install hxCodec 2.6.1
          haxelib git linc_luajit https://github.com/Default-name123/luashitjict.git
          haxelib git extension-androidtools https://github.com/Default-name123/oldtools.git
          haxelib install hxcpp-debug-server
          haxelib list
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib set flixel-addons 2.11.0
          haxelib set flixel 4.11.0
          haxelib set openfl 9.1.0
          haxelib set lime 7.9.0
          haxelib set hxCodec 2.6.1
          haxelib set hxcpp 4.2.1
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Building
        run: haxelib run lime build android -release

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/debug
          if-no-files-found: warn
  Publish:
    needs: Android
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download
        uses: actions/download-artifact@main
        with:
           name: androidBuild
           path: ${{github.workspace}}

      - name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          prerelease: false
          automatic_release_tag: 'v1.2'
          title: 'Android Port v1.2'
          files: ${{github.workspace}}/Sonic-debug.apk
